[workspace]
members = [ 
    "packages/cli",
    "packages/tyyaml"
]
resolver = "2"

[workspace.dependencies.cu]
package = "pistonite-cu"
version = "0.7.4"
# path = "../cu/packages/copper"

[workspace.dependencies]
fxhash = "0.2.1"
serde = "1"

