[package]
name = "dejj-symlist"
version = "0.0.0"
description = "Utilities for processing symbol listing"
edition = "2024"
publish = false
license = "MIT"

[dependencies]
cu = { workspace = true, features = ["print", "process"] }
llvmutils = { package = "dejj-llvmutils", path = "../llvmutils" }
dejj-utils = { path = "../utils" }
