[package]
name = "dejj-exstractor"
version = "0.0.0"
description = "Extract data from DWARF"
edition = "2024"
publish = false
license = "MIT"

[dependencies]
cu = { workspace = true, features = [ "derive", "parse" ] }
tyyaml = { path = "../tyyaml" }
exstructs = { package = "dejj-exstructs", path = "../exstructs" }
symlist = { package = "dejj-symlist", path = "../symlist" }
llvmutils = { package = "dejj-llvmutils", path = "../llvmutils" }
dejj-utils = { path = "../utils" }

serde.workspace = true 
regex.workspace = true

gimli = "0.32.1"
elf = "0.8.0"
