[package]
name = "dejj-exstructs"
version = "0.0.0"
description = "Structures used in type extraction"
edition = "2024"
publish = false
license = "MIT"

[dependencies]
cu = { workspace = true, features = [ "parse", "derive" ] }
tyyaml = { path = "../tyyaml" }
fxhash.workspace = true
serde.workspace = true
