[package]
name = "decompdb-cli"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[dependencies]
cu = { workspace = true, features = [
    "cli", "process", "toml", "json", "derive", "coroutine-heavy"
] }
tyyaml = { path = "../tyyaml" }
exstractor = { package = "dejj-exstractor", path = "../exstractor" }
exstructs = { package = "dejj-exstructs", path = "../exstructs" }
llvmutils = { package = "dejj-llvmutils", path = "../llvmutils" }
dejj-utils = { path = "../utils" }
fxhash.workspace = true
regex = "1.11.1"
serde.workspace = true
spin = "0.10.0"
tokio = "1"
shell-words.workspace = true
dashmap.workspace = true

[[bin]]
name = "decompdb"
path = "src/main.rs"
