[package]
name = "dejj-utils"
version = "0.0.0"
edition = "2024"
publish = false
license = "MIT"

[dependencies]
cu = { workspace = true, features = [
    "parse"
] }
tyyaml = { path = "../tyyaml" }

regex.workspace = true
serde.workspace = true
